import { GameType } from '@/types';

export const GAMES: GameType[] = [
  {
    slug: 'flashcards',
    title: 'Flashcards',
    description: 'Quick recall with flip cards',
    icon: 'Layers',
    minLevel: 1,
    xpPerPlay: 10,
    xpBonusPerfect: 20,
    isTimed: false,
    timeLimitSec: 0,
    color: '#60A5FA',
  },
  {
    slug: 'quiz',
    title: 'Quiz Time',
    description: 'Test your knowledge',
    icon: 'Brain',
    minLevel: 2,
    xpPerPlay: 15,
    xpBonusPerfect: 25,
    isTimed: false,
    timeLimitSec: 0,
    color: '#34D399',
  },
  {
    slug: 'timed-challenge',
    title: 'Speed Test',
    description: 'Race against the clock',
    icon: 'Timer',
    minLevel: 3,
    xpPerPlay: 20,
    xpBonusPerfect: 35,
    isTimed: true,
    timeLimitSec: 60,
    color: '#F59E0B',
  },
  {
    slug: 'matching',
    title: 'Match Up',
    description: 'Pair items together',
    icon: 'Link',
    minLevel: 4,
    xpPerPlay: 20,
    xpBonusPerfect: 30,
    isTimed: false,
    timeLimitSec: 0,
    color: '#A78BFA',
  },
  {
    slug: 'speed-round',
    title: 'Speed Round',
    description: 'Rapid-fire questions',
    icon: 'Zap',
    minLevel: 5,
    xpPerPlay: 25,
    xpBonusPerfect: 40,
    isTimed: true,
    timeLimitSec: 45,
    color: '#F472B6',
  },
  {
    slug: 'boss-battle',
    title: 'Boss Battle',
    description: 'Ultimate challenge',
    icon: 'Swords',
    minLevel: 6,
    xpPerPlay: 30,
    xpBonusPerfect: 50,
    isTimed: true,
    timeLimitSec: 120,
    color: '#EF4444',
  },
  {
    slug: 'marathon',
    title: 'Marathon',
    description: 'Endurance test',
    icon: 'Trophy',
    minLevel: 7,
    xpPerPlay: 35,
    xpBonusPerfect: 60,
    isTimed: true,
    timeLimitSec: 180,
    color: '#2ABFBF',
  },
];

export function getUnlockedGames(level: number): GameType[] {
  return GAMES.filter((game) => game.minLevel <= level);
}
